name: Packagist

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

concurrency:
  group: packagist-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    name: Notify Packagist
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Notify Packagist
        shell: bash
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
        run: |
          echo "Notifying Packagist of new release: ${{ github.ref_name }}"

          curl --fail-with-body --silent --show-error --request POST \
            --header 'content-type: application/json' \
            "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_API_TOKEN" \
            --data '{"repository":{"url":"https://packagist.org/packages/featurevisor/featurevisor-php"}}'
