name: Packagist

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    name: Notify Packagist
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Notify
        shell: bash
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
        run: |
          echo "Notifying Packagist of new release: ${{ github.event.release.tag_name }}"

          curl -X POST -H 'content-type:application/json' \
            "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_API_TOKEN" \
            -d '{"repository":{"url":"https://packagist.org/packages/featurevisor/featurevisor-php"}}'
